services:
  auth-mysql: 
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpwd
    ports:
      - "3306:3306"
    
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - "9090:9090"


networks:
  localprom:
    driver: bridge